### ISSUE TITLE
PraetorianError is not caught resulting in 500 error

### ISSUE THREAD

**Issue by idchlife** [dusktreader/flask-praetorian#125]
I'm using flask_restplus which kinda looks like the best choice to go with flask_praetorian (or in reverse order), and @api.errorhandler does not catch PraetorianError. But it does catch it's children, InvalidToken, InvalidUser etc.

~I'm wondering, is it possible to change exception class via config or maybe provide more usable for Flask exception instead of one making server go 500?~

~I'm also kinda new to Flask, so maybe exception thrown when JWT not found is ok and I just need to turn some switch on in Flask so it will handle it gracefully?~

~Thanks!~

~edit: actually, no JWT and decoding JWT errors may be more like... NotAuthrozired error or something?~

**Comment by idchlife** [comment]
@dusktreader thanks for the answer! Also using little helper.

Does yours look something like this?

![default](https://user-images.githubusercontent.com/4563032/40163898-b29e100e-59c0-11e8-969a-50bafa985412.png)

It would be very nice to have this inside flask-praetorian!

**Comment by dusktreader** [comment]
My helper actually uses the flask-restplus decorator explicitly for each exception type. Maybe not the best, but it works.

I think it's completely reasonable to add something like this in a method within flask-praetorian specifically for flask-restplus implementations.

Keep your eyes open for the next release!

**Comment by dusktreader** [comment]
@idchlife So, I decided that the helper method should actually go in FlaskBuzz since it may be useful outside of flask-praetorian

I pushed a new release of flask-buzz this morning that adds the following helper method:
    FlaskBuzz.register_error_handler_with_flask_restplus(api)

You can also call that method from PraetorianError since it derives from FlaskBuzz.

You will need to update your version of flask-buzz, however, to 0.1.7

I've also added some extra documentation about error handling to the master branch of flask-praetorian. This will go out with the next release.

Please review these topics and close this issue when you are satisfied. Thanks for the involvement!

**Comment by idchlife** [comment]
Hey, may I ask about your thoughts on adding this inside FlaskBuzz error class? I thought since it's not so connected to error-handling and more to this - not connected to flask-restplus, maybe error handler helper function should stay inside flask_praetorian, since it's (I suspect) the place everyone will expect it to be when using with flask_restplus? Also not in PraetorianError (since it's just an error, not having handler or another logic inside it), but like in

```python
from flask_praetorian.ext import restplus_api_error_handler

api = Namespace("Namespace")

restplus_api_error_handler(api)
```

or something like this?

Again, I'm not a pro in python or flask, just telling my thoughts.

Thanks!

**Comment by dusktreader** [comment]
Well, my thinking here was that the FlaskBuzz class was specifically designed to add extra stuff for automatic flask error handling. I added the error handling utility functions there because there's nothing in the functions that is specific to flask-restplus. Rather, it's specific to flask-buzz and flask-restplus. I will almost certainly need this functionality away from flask-praetorian at some point

The advantage to adding the error handling utility methods as a classmethod on FlaskBuzz is that they will be available anywhere you are using a *derived* class of FlaskBuzz. So, for instance, in flask-praetorian's main module I didn't want to import flask_buzz for one line when that module already had the PraetorianError available. I wanted to make it less confusing for users so they didn't feel like they needed to learn all about FlaskBuzz before they could understand how to set up error handling.

In this case, it's mostly a design choice. I appreciate the feedback!

**Comment by idchlife** [comment]
Got it! Thanks!
