### ISSUE TITLE
Add permissions to flask-praetorian

### ISSUE THREAD

**Issue by dusktreader** [dusktreader/flask-praetorian#162]
Sometimes users need more fine-grained control over access to users of the same class (role). For this, we should support a set of permissions.

This should be a completely optional feature.

**Comment by pahrohfit** [comment]
RBAC or just “more roles”?

What does a permission mean to an integration you would know nothing about?

Would you imagine a decorator, similar to the role, that defines a subset of developer defined tags?

**Comment by dusktreader** [comment]
Yes, it would be similar to roles in that it would be a decorator (or 2). It's just a method of adding even finer grained controls. So, you might say that a user might have the same role as another, but has been granted extra permissions.

**Comment by pahrohfit** [comment]
Would this be another table, or some kind of role extension?

Sounds messy, unless the rights breakdown are added into the role definitions as well as standalone.  If we just have another list, may as well just call them roles...

For instance, if I had a grant of “fapper”, and my roles were “op” and “mod”, without knowing what rights each of those roles provides I wouldn’t know if I had “fapper”.

This being said, for sanity, we would have to require structure (explicit breakdown) to role definitions, or not use role membership for evaluation — which seems wrong.

Decorators for role required (list must contain), disallowed (list must not contain), exact (list must be exact) seem like should cover the iterations, no?

**Comment by dusktreader** [comment]
Decided against this feature

**Comment by ademenet** [comment]
Hello,

First, thank you for all the hard work on this library. It is extremely useful!

I post here because I think I've found a “hack” to think in terms of permissions instead of roles. However, I would like to have your opinions to be sure that it doesn't create any security issues.

A role is defined by a set of permissions. For example, an admin would be the one with all permissions. Instead of thinking about roles, we could think in term of accesses or permissions. It might be useful if permissions in roles vary a lot from a user to another.

I have my users table with username, password and roles as requested by Praetorian. One user could have multiple permissions (stored in roles). My goal is to have one endpoint sending back different JSON depending on permissions. For example, let's request users list but with two kind of permissions : `get_all_users` (should return the entire list of user) and `get_user` (should return only the current user’s datas).

The code would look something like this:

```python
@pytest.route(“/users”, methods=[“GET”])
@flask_praetorian.auth_required
@flask_praetorian.roles_required([“get_all_users”, “get_user”])
def get_users():
	user = flask_praetorian.current_user()
	if user.roles == “get_all_users”:
		# Do something
		…
		return …
	elif user.roles == “get_user”:
		# Do something else
		…
		return …
	else:
		# Error
```

What do you think? Do I misunderstand the use of Praetorian? Or can it be a viable solution?

**Comment by dusktreader** [comment]
@ademenet You certainly could use the roles this way. How you use the package once inside a decorated function is up to your own creativity and, perhaps, vice. I think the idea with permissions was to possibly add another fine-grained control within roles. It is probably not going to be implemented, by the way. My current projects are not using flask-praetorian, so I have a lot less time to patch or extend it. Pull requests are always welcome, though
