### ISSUE TITLE
How to block a disabled user

### ISSUE THREAD

**Issue by forest-hou** [dusktreader/flask-praetorian#181]
Suppose we have userA logged in and is accessing the flask app. Now admin user disabled the userA. Is it possible to block userA's access immediately in flask-praetorian?

**Comment by idchlife** [comment]
@forest-hou if I'm not mistaken .is_valid @property is for this purpose.

**Comment by dusktreader** [comment]
@forest-hou The way to block a user immediately is to use the blacklist functionality on the JWT that was issued to them. Otherwise, you would have to wait for their access claim in the token to expire and they would be prevented from refreshing.

The easiest way to accomplish this without using blacklist is to set the access time limit to a low interval (say, 5 minutes). This means that a user would lose acess within 5 minutes of the user being disabled.

I'm going to close the issue, but if you need more information or need some example code, please feel free to continue commenting on this issue
