### ISSUE TITLE
Not an issue but a THANK YOU!

### ISSUE THREAD

**Issue by LBWright** [dusktreader/flask-praetorian#183]
Finally.. a Flask security module that is easy to integrate, robust, and has a long history of development.

Thank you so much guys. I was just on the edge of giving up on Flask and moving to Django - as my python framework of choice - because so many of my beloved packages were being abandoned. 

PS: I know this is not how to use github issues. But what you guys are doing is important to me. Thank you. Thank you. Thank you. And Thank you, again. :)

**Comment by idchlife** [comment]
Want also to add thank developer of this library! It's very nice to have JWT authentication library that's so easy to use in the Flask.

Also, @LBWright , what kind of libraries are being abandoned? I was using Django in the past but switched to Flask because of huge ecosystem and many many libraries, which work nicely because of Flask versions being compatible with almost all of them. Never looked back

**Comment by dusktreader** [comment]
Thank you! I appreciate the feedback a lot.

I'm going to leave this one open for a bit, I think...because reasons
