### ISSUE TITLE
Authenticating between services

### ISSUE THREAD

**Issue by iamjohnnym** [dusktreader/flask-praetorian#184]
Hello!

I apologize if this exists somewhere but I'm having issues finding it.  I'm unsure how to have a `users` service that serves authentication and user management, and then a separate service, `blogs`, that will take in credentials from the headers but authenticate against the `users` service.

Is there a documented way on how to do this?  If not, is there a recommended way?

Would there be a helper decorator that we would override on the `blog` service, that would handle that handshake between services?

**Comment by dusktreader** [comment]
flask-praetorian is not intended to be used for auth between services. So, I am just kinda speculating about this use-case.

If one of your services issues a token with flask-praetorian and the other service uses the *exact same* secret key, the token should be accepted for both services. In this case, you could simply send the token in the header of the API call between the two services. Again, though, you must use the same secrets between the two so that the hash in the token can be verified in both places.
